//
//  GameSettings.h
//  Multiplayer-Game
//
//  Created by Yhibo Blado Radlovacki Parisi on 14/05/2022.
//

#ifndef GAMESETTINGS_H
#define GAMESETTINGS_H

#define DEFAULT_START_DIRECTION DIR_UP
#define DEFAULT_START_DIRECTION_KEY 'w'

#define MAXIMUM_POWERUP_INTERVAL_SECS_MS 3000
#define MINIMUM_POWERUP_INTERVAL_SECS_MS 1000

#define MAXIMUM_BOMB_INTERVAL_SECS_MS 3000
#define MINIMUM_BOMB_INTERVAL_SECS_MS 1000
// Set 0 for no limit
#define MAXIMUM_AMOUNT_OF_BOMBS_ON_SCREEN 3
#define MAXIMUM_AMOUNT_OF_POWERUP_ON_SCREEN 2

#define KILLS_TO_WIN 3

#define GAME_UPDATE_RATE_NS 40000000

#define GAME_UPDATE_PROJ_SHIP_RATIO 3

#define GAME_READ_USER_INPUT_UPDATE_RATE_NS 150000000

#define POWERUP_DURATION 1

#define MAX_NAME_LENGTH 254

// All consoles will have the same size of the map
#define MAP_HEIGHT 80
#define MAP_WIDTH 100

#define PROMPT_SCREEN_DELAY_SEC 2

#define HALF_DELAY_GET_CHAR_IN_TENTH_OF_A_SEC 5

#define OBJECT_HALFSIZE_IN_PIXELS 1
#define SHIP_HALFSIZE_IN_PIXELS 2

#endif //GAMESETTINGS_H

